#!/bin/bash

# Copy the new jar to the build location
cp -f test/target/*.jar jenkins/build/

echo "****************************"
echo "** Building Docker Image ***"
echo "****************************"

cd jenkins/build/ && docker-compose build --no-cache