#!/bin/bash

# Copy the new jar to the build location
cp -f scripts/app/target/*.jar app.jar

echo "****************************"
echo "** Building Docker Image ***"
echo "****************************"

docker-compose build --no-cache