#!/bin/bash

echo "***************************"
echo "** Building jar ***********"
echo "***************************"

WORKSPACE=/var/lib/jenkins/workspace/test

docker run --rm  -v  $WORKSPACE/scripts/app:/app -v /root/.m2/:/root/.m2/ -w /app maven:alpine "$@"